### ISSUE TITLE
Help Me!

### ISSUE THREAD

**Issue by svoboda18** [kuronosan/KK-Kernel-MT6572#4]
I have a 3.10.89 kernel working in almost MT6572 KK 
BUT HOW I CAN PORT IT TO MY LENOVO A319?
ANY SUGGUTION WILL BE ACCEPTED
REGARDS
MR13DX
HOPE YOU HELP ME😃😃😃

**Comment by svoboda18** [comment]
ONLY WHAT IS THE FILLES I CHANGE TO BOOT IT AND MAKE IT WORKING?
SOURCES CODES HERE:
https://github.com/darklord4822/android_kernel_lenovo_a369i&hl=ar-DZ&tg=793&tk=yqIv_myLaOdqD7vR

https://github.com/darklord4822/android_kernel_lg_l60&hl=ar-DZ&tg=816&tk=yqIv_myLaOdqD7vR

https://github.com/darklord4822/android_kernel_alcatel_4027d&hl=ar-DZ&tg=920&tk=yqIv_myLaOdqD7vR


THANKS TO YOU AND SRT TEAM FOR SOURCES.

**Comment by qingzheng0723** [comment]
Thank you for your email. I'm on holiday, but I still check my email box andrespond when I have Internet connection. For urgent matters.
